name: CosmicSMPRevamped
version: 1.1.0
main: withicality.csmp.CosmicPlugin
api-version: 1.19
authors: [ Withicality ]
description: Plugin for CosmicSMP
website: withicality.tk
depend:
  - ProtocolLib
  - WorldEdit
  - SuperVanish
  - DiscordSRV